---
- hosts: all
  become: true
  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
    - name: add Kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: add Kubernetes APT repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'
 
    - name: install kubelet
      apt:
        name: kubelet=1.20.0
        state: present
      update_cache: true
 
    - name: install kubeadm
      apt:
        name: kubeadm=1.20.0
        state: present
      update_cache: true
 
    - name: install kubectl
      apt:
        name: kubectl=1.20.0
        state: present
      update_cache: true