---
- hosts: all
  become: true
  tasks:
    - name: Set timezone to Asia/Jakarta 
      timezone:
        name: Asia/Jakarta

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: add Kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: add Kubernetes APT repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'
    - name: Update Repository
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes 

    - name: remove package
      apt: name={{ item }} state=absent
      loop: [ 'kubeadm', 'kubelet', 'kubectl']

    - name: install kubelet
      apt:
        name: kubelet=1.20.0-00
        state: present
 
    - name: install kubeadm
      apt:
        name: kubeadm=1.20.0-00
        state: present
 
    - name: install kubectl
      apt:
        name: kubectl=1.20.0-00
        state: present
        allow_downgrade: yes

    - name: Hold kubeadm kubelet kubectl
      dpkg_selections: name={{ item }} selection=hold
      loop: [ 'kubeadm', 'kubelet', 'kubectl']