name: deploy playbook
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: list files
        run: ls -lah
      - name: copy all playbook
        run: sudo cp *.yml /root/aut-kube/
      - name: copy ansible.cfg
        run: sudo cp ansible.cfg /root/aut-kube/

