name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: testing linux command on self-hosted runner
        run: cat /etc/os-release
      - name: check user login
        run: w
      - name: check user home directory
        run: pwd
