name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: testing linux command on self-hosted runner
        run: cat /etc/os-release
